### ISSUE TITLE
Generate survivor function is missing which is causing error

### ISSUE THREAD

**Issue by BhawaniSingh** [Shpigford/society-fail#2]
generateSurvivor() function is called here https://github.com/Shpigford/society-fail/blob/main/javascript/game.js#L955, but the function is not defined, and because of that watchtower missions never succeed.
To fix this, I added the following method and it fixed the issue:
```js
function generateSurvivor() {
    let availableNames = [...names];
    const randomIndex = Math.floor(Math.random() * availableNames.length);
    const name = availableNames[randomIndex];
    return {
        name: name,
        health: 100,
        hunger: 0,
        thirst: 0,
        energy: 100,
        traits: {
            hungerRate: getRandomTrait('hungerRate'),
            thirstRate: getRandomTrait('thirstRate'),
            energyRate: getRandomTrait('energyRate'),
            maxEnergy: Math.round(getRandomTrait('maxEnergy')),
            energyRecoveryRate: getRandomTrait('energyRecoveryRate')
        }
    };
}
```

This resolves the issue, but it should also check for existing names so that duplicate names(survivor or players) are not generated

**Comment by Shpigford** [comment]
@BhawaniSingh Thank you so much for this! I actually just rebuilt the whole thing from scratch, so hopefully the two issues you opened have been resolved with it.
